# Generated by Django 6.0.1 on 2026-01-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=155)),
                ('source', models.CharField(max_length=155)),
                ('destination', models.CharField(max_length=155)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'train',
                'ordering': ['train_number'],
                'indexes': [models.Index(fields=['source', 'destination'], name='train_source_8d68ee_idx'), models.Index(fields=['train_number'], name='train_train_n_3e84bc_idx')],
            },
        ),
    ]
