# Generated by Django 6.0.1 on 2026-02-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_train_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
